[package]
name = "rspc"
description = "A blazing fast and easy to use TRPC server for Rust."
version = "0.1.2"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
include = ["/src", "/LICENCE", "/README.md"]
repository = "https://github.com/oscartbeaumont/rspc"
documentation = "https://docs.rs/rspc/latest/rspc"
keywords = ["async", "specta", "rust-to-ts", "typescript", "typesafe"]
categories = ["web-programming", "asynchronous"]

[features]
default = []
tauri = ["dep:tauri"]
tracing = ["dep:tracing"]
httpz = ["dep:httpz", "httpz/tokio-ws", "httpz/axum"] # Axum feature always enabled because we use the extractors regardless of webserver
# openapi = ["dep:openapiv3"]
# playground = []

# Webservers
axum = ["httpz/axum"]
actix-web = ["httpz/actix-web"]
# poem = ["httpz/poem"]
rocket = ["httpz/rocket"]
# warp = ["httpz/warp"]
lambda = ["httpz/lambda"]
workers = ["httpz/workers"]

# Specta
uuid = ["specta/uuid"]
chrono = ["specta/chrono"]
time = ["specta/time"]
bigdecimal = ["specta/bigdecimal"]
rust_decimal = ["specta/rust_decimal"]
indexmap = ["specta/indexmap"]
ipnetwork = ["specta/ipnetwork"]
mac_address = ["specta/mac_address"]
bit-vec = ["specta/bit-vec"]
bson = ["specta/bson"]

[dependencies]
specta = { version = "0.0.4", path = "./specta", features = ["serde"] }
httpz = { git = "https://github.com/oscartbeaumont/httpz.git", optional = true } # TODO: Move back to crates.io release
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
thiserror = "1.0.36"
futures = "0.3.24"
tokio = { version = "1.21.2", features = ["sync", "rt", "macros"] }
tauri = { version = "1.1.1", optional = true }
tracing = { version = "0.1.36", optional = true }
async-stream = "0.3.3"

[dev-dependencies]
async-stream = "0.3.3"

[workspace]
members = [
    "./create-rspc-app",
    "./examples",
    "./examples/axum",
    "./specta",
    "./specta/macros"
]
